apiVersion: v1
kind: Service
metadata:
  name: {{ include "experiment-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "experiment-app.name" . }}
    helm.sh/chart: {{ include "experiment-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }} 
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - {{ .Values.service.secGrp }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "experiment-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
